// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATABASE_URL: string;
	OIDC_CLIENT_ID: string;
	OIDC_CLIENT_SECRET: string;
	OIDC_CLIENT_REDIRECT_URI: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ENDPOINT: string;
	R2_BUCKET_NAME: string;
	RUNPOD_API_TOKEN: string;
	RUNPOD_ENDPOINT_HI3D_FIRST_MODEL_512: string;
}
