#:schema node_modules/wrangler/config-schema.json
name = "tokimeki-ai-app"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"