// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file api/v1/artifact/api.proto (package api.v1.artifact, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelArtifactRequest, CancelArtifactResponse, CreateArtifactRequest, CreateArtifactResponse, DeleteArtifactRequest, DeleteArtifactResponse, GetArtifactRequest, GetArtifactResponse, ListArtifactsRequest, ListArtifactsResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.artifact.Service
 */
export const Service = {
  typeName: "api.v1.artifact.Service",
  methods: {
    /**
     * @generated from rpc api.v1.artifact.Service.ListArtifacts
     */
    listArtifacts: {
      name: "ListArtifacts",
      I: ListArtifactsRequest,
      O: ListArtifactsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.artifact.Service.GetArtifact
     */
    getArtifact: {
      name: "GetArtifact",
      I: GetArtifactRequest,
      O: GetArtifactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.artifact.Service.CreateArtifact
     */
    createArtifact: {
      name: "CreateArtifact",
      I: CreateArtifactRequest,
      O: CreateArtifactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.artifact.Service.CancelArtifact
     */
    cancelArtifact: {
      name: "CancelArtifact",
      I: CancelArtifactRequest,
      O: CancelArtifactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.artifact.Service.DeleteArtifact
     */
    deleteArtifact: {
      name: "DeleteArtifact",
      I: DeleteArtifactRequest,
      O: DeleteArtifactResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

