// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file api/v1/character/api.proto (package api.v1.character, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateCharacterRequest, CreateCharacterResponse, DeleteCharacterRequest, DeleteCharacterResponse, GetCharacterRequest, GetCharacterResponse, ListCharactersRequest, ListCharactersResponse, UpdateCharacterRequest, UpdateCharacterResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.character.Service
 */
export const Service = {
  typeName: "api.v1.character.Service",
  methods: {
    /**
     * @generated from rpc api.v1.character.Service.ListCharacters
     */
    listCharacters: {
      name: "ListCharacters",
      I: ListCharactersRequest,
      O: ListCharactersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.character.Service.GetCharacter
     */
    getCharacter: {
      name: "GetCharacter",
      I: GetCharacterRequest,
      O: GetCharacterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.character.Service.CreateCharacter
     */
    createCharacter: {
      name: "CreateCharacter",
      I: CreateCharacterRequest,
      O: CreateCharacterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.character.Service.UpdateCharacter
     */
    updateCharacter: {
      name: "UpdateCharacter",
      I: UpdateCharacterRequest,
      O: UpdateCharacterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.character.Service.DeleteCharacter
     */
    deleteCharacter: {
      name: "DeleteCharacter",
      I: DeleteCharacterRequest,
      O: DeleteCharacterResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

