// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=.ts"
// @generated from file api/v1/character/api.proto (package api.v1.character, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Character } from "../../../model/v1/character_pb.ts";
import { file_model_v1_character } from "../../../model/v1/character_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/character/api.proto.
 */
export const file_api_v1_character_api: GenFile = /*@__PURE__*/
  fileDesc("ChphcGkvdjEvY2hhcmFjdGVyL2FwaS5wcm90bxIQYXBpLnYxLmNoYXJhY3RlciIXChVMaXN0Q2hhcmFjdGVyc1JlcXVlc3QiQQoWTGlzdENoYXJhY3RlcnNSZXNwb25zZRInCgpjaGFyYWN0ZXJzGAEgAygLMhMubW9kZWwudjEuQ2hhcmFjdGVyIisKE0dldENoYXJhY3RlclJlcXVlc3QSFAoMY2hhcmFjdGVyX2lkGAEgASgJIj4KFEdldENoYXJhY3RlclJlc3BvbnNlEiYKCWNoYXJhY3RlchgBIAEoCzITLm1vZGVsLnYxLkNoYXJhY3RlciI+ChZDcmVhdGVDaGFyYWN0ZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkSFgoOdGh1bWJuYWlsX3BhdGgYAiABKAkiQQoXQ3JlYXRlQ2hhcmFjdGVyUmVzcG9uc2USJgoJY2hhcmFjdGVyGAEgASgLMhMubW9kZWwudjEuQ2hhcmFjdGVyIkAKFlVwZGF0ZUNoYXJhY3RlclJlcXVlc3QSJgoJY2hhcmFjdGVyGAEgASgLMhMubW9kZWwudjEuQ2hhcmFjdGVyIkEKF1VwZGF0ZUNoYXJhY3RlclJlc3BvbnNlEiYKCWNoYXJhY3RlchgBIAEoCzITLm1vZGVsLnYxLkNoYXJhY3RlciIuChZEZWxldGVDaGFyYWN0ZXJSZXF1ZXN0EhQKDGNoYXJhY3Rlcl9pZBgBIAEoCSIZChdEZWxldGVDaGFyYWN0ZXJSZXNwb25zZTKPBAoHU2VydmljZRJlCg5MaXN0Q2hhcmFjdGVycxInLmFwaS52MS5jaGFyYWN0ZXIuTGlzdENoYXJhY3RlcnNSZXF1ZXN0GiguYXBpLnYxLmNoYXJhY3Rlci5MaXN0Q2hhcmFjdGVyc1Jlc3BvbnNlIgASXwoMR2V0Q2hhcmFjdGVyEiUuYXBpLnYxLmNoYXJhY3Rlci5HZXRDaGFyYWN0ZXJSZXF1ZXN0GiYuYXBpLnYxLmNoYXJhY3Rlci5HZXRDaGFyYWN0ZXJSZXNwb25zZSIAEmgKD0NyZWF0ZUNoYXJhY3RlchIoLmFwaS52MS5jaGFyYWN0ZXIuQ3JlYXRlQ2hhcmFjdGVyUmVxdWVzdBopLmFwaS52MS5jaGFyYWN0ZXIuQ3JlYXRlQ2hhcmFjdGVyUmVzcG9uc2UiABJoCg9VcGRhdGVDaGFyYWN0ZXISKC5hcGkudjEuY2hhcmFjdGVyLlVwZGF0ZUNoYXJhY3RlclJlcXVlc3QaKS5hcGkudjEuY2hhcmFjdGVyLlVwZGF0ZUNoYXJhY3RlclJlc3BvbnNlIgASaAoPRGVsZXRlQ2hhcmFjdGVyEiguYXBpLnYxLmNoYXJhY3Rlci5EZWxldGVDaGFyYWN0ZXJSZXF1ZXN0GikuYXBpLnYxLmNoYXJhY3Rlci5EZWxldGVDaGFyYWN0ZXJSZXNwb25zZSIAQoIBChRjb20uYXBpLnYxLmNoYXJhY3RlckIIQXBpUHJvdG9QAaICA0FWQ6oCEEFwaS5WMS5DaGFyYWN0ZXLKAhBBcGlcVjFcQ2hhcmFjdGVy4gIcQXBpXFYxXENoYXJhY3RlclxHUEJNZXRhZGF0YeoCEkFwaTo6VjE6OkNoYXJhY3RlcmIGcHJvdG8z", [file_model_v1_character]);

/**
 * @generated from message api.v1.character.ListCharactersRequest
 */
export type ListCharactersRequest = Message<"api.v1.character.ListCharactersRequest"> & {
};

/**
 * Describes the message api.v1.character.ListCharactersRequest.
 * Use `create(ListCharactersRequestSchema)` to create a new message.
 */
export const ListCharactersRequestSchema: GenMessage<ListCharactersRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 0);

/**
 * @generated from message api.v1.character.ListCharactersResponse
 */
export type ListCharactersResponse = Message<"api.v1.character.ListCharactersResponse"> & {
  /**
   * @generated from field: repeated model.v1.Character characters = 1;
   */
  characters: Character[];
};

/**
 * Describes the message api.v1.character.ListCharactersResponse.
 * Use `create(ListCharactersResponseSchema)` to create a new message.
 */
export const ListCharactersResponseSchema: GenMessage<ListCharactersResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 1);

/**
 * @generated from message api.v1.character.GetCharacterRequest
 */
export type GetCharacterRequest = Message<"api.v1.character.GetCharacterRequest"> & {
  /**
   * @generated from field: string character_id = 1;
   */
  characterId: string;
};

/**
 * Describes the message api.v1.character.GetCharacterRequest.
 * Use `create(GetCharacterRequestSchema)` to create a new message.
 */
export const GetCharacterRequestSchema: GenMessage<GetCharacterRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 2);

/**
 * @generated from message api.v1.character.GetCharacterResponse
 */
export type GetCharacterResponse = Message<"api.v1.character.GetCharacterResponse"> & {
  /**
   * @generated from field: model.v1.Character character = 1;
   */
  character?: Character;
};

/**
 * Describes the message api.v1.character.GetCharacterResponse.
 * Use `create(GetCharacterResponseSchema)` to create a new message.
 */
export const GetCharacterResponseSchema: GenMessage<GetCharacterResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 3);

/**
 * @generated from message api.v1.character.CreateCharacterRequest
 */
export type CreateCharacterRequest = Message<"api.v1.character.CreateCharacterRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string thumbnail_path = 2;
   */
  thumbnailPath: string;
};

/**
 * Describes the message api.v1.character.CreateCharacterRequest.
 * Use `create(CreateCharacterRequestSchema)` to create a new message.
 */
export const CreateCharacterRequestSchema: GenMessage<CreateCharacterRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 4);

/**
 * @generated from message api.v1.character.CreateCharacterResponse
 */
export type CreateCharacterResponse = Message<"api.v1.character.CreateCharacterResponse"> & {
  /**
   * @generated from field: model.v1.Character character = 1;
   */
  character?: Character;
};

/**
 * Describes the message api.v1.character.CreateCharacterResponse.
 * Use `create(CreateCharacterResponseSchema)` to create a new message.
 */
export const CreateCharacterResponseSchema: GenMessage<CreateCharacterResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 5);

/**
 * @generated from message api.v1.character.UpdateCharacterRequest
 */
export type UpdateCharacterRequest = Message<"api.v1.character.UpdateCharacterRequest"> & {
  /**
   * @generated from field: model.v1.Character character = 1;
   */
  character?: Character;
};

/**
 * Describes the message api.v1.character.UpdateCharacterRequest.
 * Use `create(UpdateCharacterRequestSchema)` to create a new message.
 */
export const UpdateCharacterRequestSchema: GenMessage<UpdateCharacterRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 6);

/**
 * @generated from message api.v1.character.UpdateCharacterResponse
 */
export type UpdateCharacterResponse = Message<"api.v1.character.UpdateCharacterResponse"> & {
  /**
   * @generated from field: model.v1.Character character = 1;
   */
  character?: Character;
};

/**
 * Describes the message api.v1.character.UpdateCharacterResponse.
 * Use `create(UpdateCharacterResponseSchema)` to create a new message.
 */
export const UpdateCharacterResponseSchema: GenMessage<UpdateCharacterResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 7);

/**
 * @generated from message api.v1.character.DeleteCharacterRequest
 */
export type DeleteCharacterRequest = Message<"api.v1.character.DeleteCharacterRequest"> & {
  /**
   * @generated from field: string character_id = 1;
   */
  characterId: string;
};

/**
 * Describes the message api.v1.character.DeleteCharacterRequest.
 * Use `create(DeleteCharacterRequestSchema)` to create a new message.
 */
export const DeleteCharacterRequestSchema: GenMessage<DeleteCharacterRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 8);

/**
 * @generated from message api.v1.character.DeleteCharacterResponse
 */
export type DeleteCharacterResponse = Message<"api.v1.character.DeleteCharacterResponse"> & {
};

/**
 * Describes the message api.v1.character.DeleteCharacterResponse.
 * Use `create(DeleteCharacterResponseSchema)` to create a new message.
 */
export const DeleteCharacterResponseSchema: GenMessage<DeleteCharacterResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_character_api, 9);

/**
 * @generated from service api.v1.character.Service
 */
export const Service: GenService<{
  /**
   * @generated from rpc api.v1.character.Service.ListCharacters
   */
  listCharacters: {
    methodKind: "unary";
    input: typeof ListCharactersRequestSchema;
    output: typeof ListCharactersResponseSchema;
  },
  /**
   * @generated from rpc api.v1.character.Service.GetCharacter
   */
  getCharacter: {
    methodKind: "unary";
    input: typeof GetCharacterRequestSchema;
    output: typeof GetCharacterResponseSchema;
  },
  /**
   * @generated from rpc api.v1.character.Service.CreateCharacter
   */
  createCharacter: {
    methodKind: "unary";
    input: typeof CreateCharacterRequestSchema;
    output: typeof CreateCharacterResponseSchema;
  },
  /**
   * @generated from rpc api.v1.character.Service.UpdateCharacter
   */
  updateCharacter: {
    methodKind: "unary";
    input: typeof UpdateCharacterRequestSchema;
    output: typeof UpdateCharacterResponseSchema;
  },
  /**
   * @generated from rpc api.v1.character.Service.DeleteCharacter
   */
  deleteCharacter: {
    methodKind: "unary";
    input: typeof DeleteCharacterRequestSchema;
    output: typeof DeleteCharacterResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_character_api, 0);

