// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=.ts"
// @generated from file model/v1/artifact.proto (package model.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/v1/artifact.proto.
 */
export const file_model_v1_artifact: GenFile = /*@__PURE__*/
  fileDesc("Chdtb2RlbC92MS9hcnRpZmFjdC5wcm90bxIIbW9kZWwudjEiIwoNQXJ0aWZhY3RJbnB1dBISCgppbWFnZV9wYXRoGAEgASgJInkKCEFydGlmYWN0EgoKAmlkGAEgASgJEg4KBnN0YXR1cxgCIAEoCRIUCgxvYmplY3RfcGF0aHMYAyADKAkSEwoLb2JqZWN0X3VybHMYBCADKAkSEgoKY3JlYXRlZF9hdBgFIAEoBRISCgp1cGRhdGVkX2F0GAYgASgFQl4KDGNvbS5tb2RlbC52MUINQXJ0aWZhY3RQcm90b1ABogIDTVhYqgIITW9kZWwuVjHKAghNb2RlbFxWMeICFE1vZGVsXFYxXEdQQk1ldGFkYXRh6gIJTW9kZWw6OlYxYgZwcm90bzM");

/**
 * @generated from message model.v1.ArtifactInput
 */
export type ArtifactInput = Message<"model.v1.ArtifactInput"> & {
  /**
   * @generated from field: string image_path = 1;
   */
  imagePath: string;
};

/**
 * Describes the message model.v1.ArtifactInput.
 * Use `create(ArtifactInputSchema)` to create a new message.
 */
export const ArtifactInputSchema: GenMessage<ArtifactInput> = /*@__PURE__*/
  messageDesc(file_model_v1_artifact, 0);

/**
 * @generated from message model.v1.Artifact
 */
export type Artifact = Message<"model.v1.Artifact"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: repeated string object_paths = 3;
   */
  objectPaths: string[];

  /**
   * @generated from field: repeated string object_urls = 4;
   */
  objectUrls: string[];

  /**
   * @generated from field: int32 created_at = 5;
   */
  createdAt: number;

  /**
   * @generated from field: int32 updated_at = 6;
   */
  updatedAt: number;
};

/**
 * Describes the message model.v1.Artifact.
 * Use `create(ArtifactSchema)` to create a new message.
 */
export const ArtifactSchema: GenMessage<Artifact> = /*@__PURE__*/
  messageDesc(file_model_v1_artifact, 1);

