// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=.ts"
// @generated from file model/v1/character.proto (package model.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/v1/character.proto.
 */
export const file_model_v1_character: GenFile = /*@__PURE__*/
  fileDesc("Chhtb2RlbC92MS9jaGFyYWN0ZXIucHJvdG8SCG1vZGVsLnYxIlQKCUNoYXJhY3RlchIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhYKDnRodW1ibmFpbF9wYXRoGAMgASgJEhUKDXRodW1ibmFpbF91cmwYBCABKAlCXwoMY29tLm1vZGVsLnYxQg5DaGFyYWN0ZXJQcm90b1ABogIDTVhYqgIITW9kZWwuVjHKAghNb2RlbFxWMeICFE1vZGVsXFYxXEdQQk1ldGFkYXRh6gIJTW9kZWw6OlYxYgZwcm90bzM");

/**
 * @generated from message model.v1.Character
 */
export type Character = Message<"model.v1.Character"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string thumbnail_path = 3;
   */
  thumbnailPath: string;

  /**
   * @generated from field: string thumbnail_url = 4;
   */
  thumbnailUrl: string;
};

/**
 * Describes the message model.v1.Character.
 * Use `create(CharacterSchema)` to create a new message.
 */
export const CharacterSchema: GenMessage<Character> = /*@__PURE__*/
  messageDesc(file_model_v1_character, 0);

