// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.ts"
// @generated from file model/v1/character.proto (package model.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message model.v1.Character
 */
export class Character extends Message<Character> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string thumbnail_path = 3;
   */
  thumbnailPath = "";

  /**
   * @generated from field: string thumbnail_url = 4;
   */
  thumbnailUrl = "";

  constructor(data?: PartialMessage<Character>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "model.v1.Character";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "thumbnail_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "thumbnail_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Character {
    return new Character().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Character {
    return new Character().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Character {
    return new Character().fromJsonString(jsonString, options);
  }

  static equals(a: Character | PlainMessage<Character> | undefined, b: Character | PlainMessage<Character> | undefined): boolean {
    return proto3.util.equals(Character, a, b);
  }
}

