// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=.ts"
// @generated from file model/v1/session.proto (package model.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/v1/session.proto.
 */
export const file_model_v1_session: GenFile = /*@__PURE__*/
  fileDesc("ChZtb2RlbC92MS9zZXNzaW9uLnByb3RvEghtb2RlbC52MSIVCgdTZXNzaW9uEgoKAmlkGAEgASgJQl0KDGNvbS5tb2RlbC52MUIMU2Vzc2lvblByb3RvUAGiAgNNWFiqAghNb2RlbC5WMcoCCE1vZGVsXFYx4gIUTW9kZWxcVjFcR1BCTWV0YWRhdGHqAglNb2RlbDo6VjFiBnByb3RvMw");

/**
 * @generated from message model.v1.Session
 */
export type Session = Message<"model.v1.Session"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message model.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema: GenMessage<Session> = /*@__PURE__*/
  messageDesc(file_model_v1_session, 0);

