// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=.ts"
// @generated from file model/v1/user.proto (package model.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/v1/user.proto.
 */
export const file_model_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChNtb2RlbC92MS91c2VyLnByb3RvEghtb2RlbC52MSISCgRVc2VyEgoKAmlkGAEgASgJQloKDGNvbS5tb2RlbC52MUIJVXNlclByb3RvUAGiAgNNWFiqAghNb2RlbC5WMcoCCE1vZGVsXFYx4gIUTW9kZWxcVjFcR1BCTWV0YWRhdGHqAglNb2RlbDo6VjFiBnByb3RvMw");

/**
 * @generated from message model.v1.User
 */
export type User = Message<"model.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message model.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_model_v1_user, 0);

