// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=.ts"
// @generated from file api/v1/user/api.proto (package api.v1.user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { User } from "../../../model/v1/user_pb.ts";
import { file_model_v1_user } from "../../../model/v1/user_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/user/api.proto.
 */
export const file_api_v1_user_api: GenFile = /*@__PURE__*/
  fileDesc("ChVhcGkvdjEvdXNlci9hcGkucHJvdG8SC2FwaS52MS51c2VyIg4KDFdob2lzUmVxdWVzdCItCg1XaG9pc1Jlc3BvbnNlEhwKBHVzZXIYASABKAsyDi5tb2RlbC52MS5Vc2VyMksKB1NlcnZpY2USQAoFV2hvaXMSGS5hcGkudjEudXNlci5XaG9pc1JlcXVlc3QaGi5hcGkudjEudXNlci5XaG9pc1Jlc3BvbnNlIgBCaQoPY29tLmFwaS52MS51c2VyQghBcGlQcm90b1ABogIDQVZVqgILQXBpLlYxLlVzZXLKAgtBcGlcVjFcVXNlcuICF0FwaVxWMVxVc2VyXEdQQk1ldGFkYXRh6gINQXBpOjpWMTo6VXNlcmIGcHJvdG8z", [file_model_v1_user]);

/**
 * @generated from message api.v1.user.WhoisRequest
 */
export type WhoisRequest = Message<"api.v1.user.WhoisRequest"> & {
};

/**
 * Describes the message api.v1.user.WhoisRequest.
 * Use `create(WhoisRequestSchema)` to create a new message.
 */
export const WhoisRequestSchema: GenMessage<WhoisRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_api, 0);

/**
 * @generated from message api.v1.user.WhoisResponse
 */
export type WhoisResponse = Message<"api.v1.user.WhoisResponse"> & {
  /**
   * @generated from field: model.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message api.v1.user.WhoisResponse.
 * Use `create(WhoisResponseSchema)` to create a new message.
 */
export const WhoisResponseSchema: GenMessage<WhoisResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_user_api, 1);

/**
 * @generated from service api.v1.user.Service
 */
export const Service: GenService<{
  /**
   * @generated from rpc api.v1.user.Service.Whois
   */
  whois: {
    methodKind: "unary";
    input: typeof WhoisRequestSchema;
    output: typeof WhoisResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_user_api, 0);

