// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file api/v1/user/api.proto (package api.v1.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { WhoisRequest, WhoisResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.user.Service
 */
export const Service = {
  typeName: "api.v1.user.Service",
  methods: {
    /**
     * @generated from rpc api.v1.user.Service.Whois
     */
    whois: {
      name: "Whois",
      I: WhoisRequest,
      O: WhoisResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

