// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file api/v1/storage/api.proto (package api.v1.storage, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUploadUrlRequest, CreateUploadUrlResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.storage.Service
 */
export const Service = {
  typeName: "api.v1.storage.Service",
  methods: {
    /**
     * @generated from rpc api.v1.storage.Service.CreateUploadUrl
     */
    createUploadUrl: {
      name: "CreateUploadUrl",
      I: CreateUploadUrlRequest,
      O: CreateUploadUrlResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

